version: '3.1'

services:
  php:
    # image: php:7.4-apache
    build: ./php
    ports:
      - 5000:80
    volumes:
      - ./public:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      # - ./db-data:/var/lib/mysql
      - php-dev-mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  php-dev-mysql: 
